### ISSUE TITLE
Bleadperl v5.31.9-131-g02b85d3dab breaks Perl-Lexer-0.31.tar.gz

### ISSUE THREAD

**Issue by andk** [tokuhirom/Perl-Lexer#10]
Changes to  perly.y and toke.c.

02b85d3dab092d678cfc958a2dc252405333ed25 is the first bad commit
commit 02b85d3dab092d678cfc958a2dc252405333ed25
Author: Zefram <zefram@fysh.org>
Date:   Wed Feb 5 07:43:14 2020 +0000

    chained comparisons

Cheers, Greetings, and Stay-Healthy-Wishes:)

**Comment by charsbar** [comment]
Thank you. Shipped 0.32 with the latest perly.y/toke.c.

And I hope you all stay well too. Cheers.
