### ISSUE TITLE
Bleadperl v5.31.2-21-g996b0cb8b8 breaks Perl-Lexer-0.29

### ISSUE THREAD

**Issue by andk** [tokuhirom/Perl-Lexer#9]
As per subject. Sample fail report: http://www.cpantesters.org/cpan/report/6fd13158-af7c-11e9-a8c2-b68dcb59f508

Link to commit: https://perl5.git.perl.org/perl.git/commit/996b0cb8b8

I suppose this is not a BBC in the sense that p5p needs to be informed. Please correct me if I'm wrong.

Regards,

**Comment by charsbar** [comment]
Thanks for your report. I'll release the next version with updated perly.y and token_info.h as soon as Perl 5.31.3 is released.

This is not a BBC. It's just that this module needs to be updated every time perly.y/toke.c is updated.
